#ifndef _msgids_
#define _msgids_

#include "cfe_mission_cfg.h"

/*
** CFE core message IDs.
*/

#define CFE_EVS_CMD_MID             CFE_MISSION_CMD_MID_BASE1 + CFE_MISSION_EVS_CMD_MSG             /* 0x1801 */
#define CFE_SB_CMD_MID              CFE_MISSION_CMD_MID_BASE1 + CFE_MISSION_SB_CMD_MSG              /* 0x1803 */
#define CFE_TBL_CMD_MID             CFE_MISSION_CMD_MID_BASE1 + CFE_MISSION_TBL_CMD_MSG             /* 0x1804 */
#define CFE_TIME_CMD_MID            CFE_MISSION_CMD_MID_BASE1 + CFE_MISSION_TIME_CMD_MSG            /* 0x1805 */
#define CFE_ES_CMD_MID              CFE_MISSION_CMD_MID_BASE1 + CFE_MISSION_ES_CMD_MSG              /* 0x1806 */
#define CFE_ES_SEND_HK_MID          CFE_MISSION_CMD_MID_BASE1 + CFE_MISSION_ES_SEND_HK_MSG          /* 0x1808 */
#define CFE_EVS_SEND_HK_MID         CFE_MISSION_CMD_MID_BASE1 + CFE_MISSION_EVS_SEND_HK_MSG         /* 0x1809 */
#define CFE_SB_SEND_HK_MID          CFE_MISSION_CMD_MID_BASE1 + CFE_MISSION_SB_SEND_HK_MSG          /* 0x180B */
#define CFE_TBL_SEND_HK_MID         CFE_MISSION_CMD_MID_BASE1 + CFE_MISSION_TBL_SEND_HK_MSG         /* 0x180C */
#define CFE_TIME_SEND_HK_MID        CFE_MISSION_CMD_MID_BASE1 + CFE_MISSION_TIME_SEND_HK_MSG        /* 0x180D */
#define CFE_TIME_TONE_CMD_MID       CFE_MISSION_CMD_MID_BASE1 + CFE_MISSION_TIME_TONE_CMD_MSG       /* 0x1810 */
#define CFE_TIME_1HZ_CMD_MID        CFE_MISSION_CMD_MID_BASE1 + CFE_MISSION_TIME_1HZ_CMD_MSG        /* 0x1811 */
#define CFE_TIME_DATA_CMD_MID       CFE_MISSION_CMD_MID_BASE_GLOB + CFE_MISSION_TIME_DATA_CMD_MSG   /* 0x1860 */
#define CFE_TIME_SEND_CMD_MID       CFE_MISSION_CMD_MID_BASE_GLOB + CFE_MISSION_TIME_SEND_CMD_MSG   /* 0x1862 */

#define CFE_ES_HK_TLM_MID           CFE_MISSION_TLM_MID_BASE1 + CFE_MISSION_ES_HK_TLM_MSG           /* 0x0800 */
#define CFE_EVS_HK_TLM_MID          CFE_MISSION_TLM_MID_BASE1 + CFE_MISSION_EVS_HK_TLM_MSG          /* 0x0801 */
#define CFE_SB_HK_TLM_MID           CFE_MISSION_TLM_MID_BASE1 + CFE_MISSION_SB_HK_TLM_MSG           /* 0x0803 */
#define CFE_TBL_HK_TLM_MID          CFE_MISSION_TLM_MID_BASE1 + CFE_MISSION_TBL_HK_TLM_MSG          /* 0x0804 */
#define CFE_TIME_HK_TLM_MID         CFE_MISSION_TLM_MID_BASE1 + CFE_MISSION_TIME_HK_TLM_MSG         /* 0x0805 */
#define CFE_TIME_DIAG_TLM_MID       CFE_MISSION_TLM_MID_BASE1 + CFE_MISSION_TIME_DIAG_TLM_MSG       /* 0x0806 */
#define CFE_EVS_LONG_EVENT_MSG_MID  CFE_MISSION_TLM_MID_BASE1 + CFE_MISSION_EVS_LONG_EVENT_MSG_MSG  /* 0x0808 */
#define CFE_EVS_SHORT_EVENT_MSG_MID CFE_MISSION_TLM_MID_BASE1 + CFE_MISSION_EVS_SHORT_EVENT_MSG_MSG /* 0x0809 */
#define CFE_SB_STATS_TLM_MID        CFE_MISSION_TLM_MID_BASE1 + CFE_MISSION_SB_STATS_TLM_MSG        /* 0x080A */
#define CFE_ES_APP_TLM_MID          CFE_MISSION_TLM_MID_BASE1 + CFE_MISSION_ES_APP_TLM_MSG          /* 0x080B */
#define CFE_TBL_REG_TLM_MID         CFE_MISSION_TLM_MID_BASE1 + CFE_MISSION_TBL_REG_TLM_MSG         /* 0x080C */
#define CFE_SB_ALLSUBS_TLM_MID      CFE_MISSION_TLM_MID_BASE1 + CFE_MISSION_SB_ALLSUBS_TLM_MSG      /* 0x080D */
#define CFE_SB_ONESUB_TLM_MID       CFE_MISSION_TLM_MID_BASE1 + CFE_MISSION_SB_ONESUB_TLM_MSG       /* 0x080E */
#define CFE_ES_SHELL_TLM_MID        CFE_MISSION_TLM_MID_BASE1 + CFE_MISSION_ES_SHELL_TLM_MSG        /* 0x080F */
#define CFE_ES_MEMSTATS_TLM_MID     CFE_MISSION_TLM_MID_BASE1 + CFE_MISSION_ES_MEMSTATS_TLM_MSG     /* 0x0810 */

#ifndef CFE_OMIT_DEPRECATED_6_6
#define CFE_EVS_EVENT_MSG_MID CFE_EVS_LONG_EVENT_MSG_MID
#endif

/*
** User-application message IDs.
*/

#define SCH_INIT_DONE_MID (0x1905)

#define REPLICA_READ_SENSOR_MID         (0x1910)
#define REPLICA_START_COMPUTE_MID       (0x1911)
#define REPLICA_SEND_ACTUATOR_MID       (0x1912)
#define REPLICA_START_AGREEMENT_MID     (0x1913)
#define REPLICA_START_SOURCE_SELECT_MID (0x1914)
#define REPLICA_FILTER_SENSOR_MID       (0x1915)
    
#define SIM_SEND_SENSOR_MID   (0x1950)
#define SIM_READ_ACTUATOR_MID (0x1951)

#endif

